# Generated by Django 2.2.4 on 2019-09-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190826_1429'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('city', 'loc')},
        ),
    ]
